Theory and Practice of FEM -- a parametrized Poisson Solver: BaseBlockProblem< dim > Class Template Reference
BaseBlockProblem< dim > Class Template Reference
#include <base_block_problem.h>
Public Types
using CopyData = typename BaseProblem< dim >::CopyData
using ScratchData = typename BaseProblem< dim >::ScratchData
Public Types inherited from BaseProblem< dim >
using CopyData = MeshWorker::CopyData< 1, 1, 1 >
using ScratchData = MeshWorker::ScratchData< dim >
Public Member Functions
BaseBlockProblem (const std::vector< std::string > component_names={{"u"}}, const std::string &problem_name="")
virtual ~BaseBlockProblem ()=default
Public Member Functions inherited from BaseProblem< dim >
BaseProblem (const unsigned int &n_components=1, const std::string &problem_name="")
virtual ~BaseProblem ()=default
void print_system_info ()
void run ()
void initialize (const std::string &filename)
void parse_string (const std::string &par)
Public Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
virtual ~ParameterAcceptor () override
virtual void declare_parameters (ParameterHandler &prm)
virtual void parse_parameters (ParameterHandler &prm)
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from Subscriptor
Subscriptor ()
Subscriptor (const Subscriptor &)
Subscriptor (Subscriptor &&) noexcept
virtual ~Subscriptor ()
Subscriptor & operator= (const Subscriptor &)
Subscriptor & operator= (Subscriptor &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Protected Member Functions
virtual void assemble_system_one_cell (const typename DoFHandler< dim >::active_cell_iterator &cell, ScratchData &scratch, CopyData &copy) override
virtual void copy_one_cell (const CopyData &copy) override
virtual void setup_system () override
virtual void assemble_system () override
virtual void solve () override
Protected Member Functions inherited from BaseProblem< dim >
void make_grid ()
virtual void estimate ()
void mark ()
void refine_grid ()
virtual void output_results (const unsigned cycle) const
Protected Attributes
const std::vector< std::string > component_names
std::vector< types::global_dof_index > dofs_per_block
std::vector< IndexSet > locally_owned_dofs
std::vector< IndexSet > locally_relevant_dofs
LA::MPI::BlockSparseMatrix system_block_matrix
LA::MPI::BlockVector locally_relevant_block_solution
LA::MPI::BlockVector block_solution
LA::MPI::BlockVector system_block_rhs
Protected Attributes inherited from BaseProblem< dim >
boost::signals2::signal< void()> setup_system_call_back
boost::signals2::signal< void(DataOut< dim > &)> add_data_vector
const unsigned int n_components
MPI_Comm mpi_communicator
int number_of_threads = -1
ConditionalOStream pcout
TimerOutput timer
parallel::distributed::Triangulation< dim > triangulation
std::unique_ptr< FiniteElement< dim > > fe
std::unique_ptr< MappingQGeneric< dim > > mapping
DoFHandler< dim > dof_handler
AffineConstraints< double > constraints
IndexSet locally_owned_dofs
IndexSet locally_relevant_dofs
LA::MPI::SparseMatrix system_matrix
LA::MPI::Vector locally_relevant_solution
LA::MPI::Vector solution
LA::MPI::Vector system_rhs
Vector< float > error_per_cell
std::string estimator_type = "exact"
std::string marking_strategy = "global"
std::pair< double, double > coarsening_and_refinement_factors = {0.03, 0.3}
FunctionParser< dim > pre_refinement
FunctionParser< dim > forcing_term
FunctionParser< dim > exact_solution
FunctionParser< dim > dirichlet_boundary_condition
FunctionParser< dim > neumann_boundary_condition
std::string fe_name = "FE_Q(1)"
unsigned int mapping_degree = 1
unsigned int n_refinements = 4
unsigned int n_refinement_cycles = 1
std::string output_filename = "linear_elasticity"
std::set< types::boundary_id > dirichlet_ids = {0}
std::set< types::boundary_id > neumann_ids
std::map< std::string, double > constants
std::string forcing_term_expression = "1"
std::string exact_solution_expression = "0"
std::string dirichlet_boundary_conditions_expression = "0"
std::string neumann_boundary_conditions_expression = "0"
std::string pre_refinement_expression = "0"
std::string grid_generator_function = "hyper_cube"
std::string grid_generator_arguments = "0: 1: false"
ParsedConvergenceTable error_table
ParameterAcceptorProxy< ReductionControl > solver_control
Protected Attributes inherited from ParameterAcceptor
const std::string section_name
std::vector< std::string > subsections
Friends
template<typename Integral >
class BaseBlockProblemTester
Additional Inherited Members
Static Public Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from Subscriptor
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Public Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
Static Public Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Detailed Description
template<int dim>
class BaseBlockProblem< dim >
BaseBlockProblem
Definition at line 37 of file base_block_problem.h.
Member Typedef Documentation
CopyData
template<int dim> using BaseBlockProblem< dim >::CopyData = typename BaseProblem<dim>::CopyData
CopyDataWorkStream
Definition at line 54 of file base_block_problem.h.
ScratchData
template<int dim> using BaseBlockProblem< dim >::ScratchData = typename BaseProblem<dim>::ScratchData
ScratchData
Definition at line 59 of file base_block_problem.h.
Constructor & Destructor Documentation
BaseBlockProblem()
template<int dim> BaseBlockProblem< dim >::BaseBlockProblem (const std::vector< std::string > component_names = {{"u"}}, const std::string & problem_name = "")
Constructor. Store component names and component masks.
Definition at line 27 of file base_block_problem.cc.
~BaseBlockProblem()
template<int dim> virtual BaseBlockProblem< dim >::~BaseBlockProblem () virtual default
Virtual destructor.
Member Function Documentation
assemble_system()
template<int dim> void BaseBlockProblem< dim >::assemble_system override protected virtual
MPI Threads
Reimplemented from BaseProblem< dim >.
Definition at line 167 of file base_block_problem.cc.
References VectorOperation::add, copy(), WorkStream::run(), update_gradients, update_JxW_values, update_quadrature_points, and update_values.
assemble_system_one_cell()
template<int dim> void BaseBlockProblem< dim >::assemble_system_one_cell (const typename DoFHandler< dim >::active_cell_iterator & cell, ScratchData & scratch, CopyData & copy) override protected virtual
cellFEValuesscratchcopy WorkStream
Parameters
cell Cell on which we assemble the local matrix and rhs.
scratch Scratch object.
copy Copy object.
Reimplemented from BaseProblem< dim >.
Reimplemented in Stokes< dim >.
Definition at line 142 of file base_block_problem.cc.
References Assert, and ExcPureFunctionCalled().
copy_one_cell()
template<int dim> void BaseBlockProblem< dim >::copy_one_cell (const CopyData & copy) override protected virtual
assemble_system_on_cell() rhs
Parameters
copy rhs
Reimplemented from BaseProblem< dim >.
Definition at line 154 of file base_block_problem.cc.
References copy().
setup_system()
template<int dim> void BaseBlockProblem< dim >::setup_system override protected virtual
Reimplemented from BaseProblem< dim >.
Definition at line 38 of file base_block_problem.cc.
References Assert, AssertDimension, DoFRenumbering::component_wise(), TrilinosWrappers::BlockSparsityPattern::compress(), DoFTools::count_dofs_per_fe_block(), ExcInternalError(), DoFTools::extract_locally_relevant_dofs(), VectorTools::interpolate_boundary_values(), locally_owned_dofs(), DoFTools::make_hanging_node_constraints(), DoFTools::make_sparsity_pattern(), IndexSet::split_by_block(), Patterns::Tools::to_string(), and triangulation.
solve()
template<int dim> void BaseBlockProblem< dim >::solve override protected virtual
Reimplemented from BaseProblem< dim >.
Reimplemented in Stokes< dim >.
Definition at line 210 of file base_block_problem.cc.
Friends And Related Function Documentation
BaseBlockProblemTester
template<int dim> template<typename Integral > friend class BaseBlockProblemTester friend
Definition at line 135 of file base_block_problem.h.
Member Data Documentation
block_solution
template<int dim> LA::MPI::BlockVector BaseBlockProblem< dim >::block_solution protected
Solution vector.
Definition at line 123 of file base_block_problem.h.
component_names
template<int dim> const std::vector<std::string> BaseBlockProblem< dim >::component_names protected
Definition at line 93 of file base_block_problem.h.
Referenced by Stokes< dim >::Stokes().
dofs_per_block
template<int dim> std::vector<types::global_dof_index> BaseBlockProblem< dim >::dofs_per_block protected
Dofs per block
Definition at line 98 of file base_block_problem.h.
locally_owned_dofs
template<int dim> std::vector<IndexSet> BaseBlockProblem< dim >::locally_owned_dofs protected
MPI
Definition at line 103 of file base_block_problem.h.
locally_relevant_block_solution
template<int dim> LA::MPI::BlockVector BaseBlockProblem< dim >::locally_relevant_block_solution protected
Definition at line 118 of file base_block_problem.h.
Referenced by Stokes< dim >::Stokes().
locally_relevant_dofs
template<int dim> std::vector<IndexSet> BaseBlockProblem< dim >::locally_relevant_dofs protected
Definition at line 108 of file base_block_problem.h.
system_block_matrix
template<int dim> LA::MPI::BlockSparseMatrix BaseBlockProblem< dim >::system_block_matrix protected
Definition at line 113 of file base_block_problem.h.
system_block_rhs
template<int dim> LA::MPI::BlockVector BaseBlockProblem< dim >::system_block_rhs protected
dofs
Definition at line 128 of file base_block_problem.h.
The documentation for this class was generated from the following files:
/github/workspace/include/base_block_problem.h
/github/workspace/source/base_block_problem.cc