Theory and Practice of FEM -- a parametrized Poisson Solver: BaseProblem< dim > Class Template Reference
BaseProblem< dim > Class Template Reference
#include <base_problem.h>
Public Types
using CopyData = MeshWorker::CopyData< 1, 1, 1 >
using ScratchData = MeshWorker::ScratchData< dim >
Public Member Functions
BaseProblem (const unsigned int &n_components=1, const std::string &problem_name="")
virtual ~BaseProblem ()=default
void print_system_info ()
void run ()
void initialize (const std::string &filename)
void parse_string (const std::string &par)
Public Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
virtual ~ParameterAcceptor () override
virtual void declare_parameters (ParameterHandler &prm)
virtual void parse_parameters (ParameterHandler &prm)
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from Subscriptor
Subscriptor ()
Subscriptor (const Subscriptor &)
Subscriptor (Subscriptor &&) noexcept
virtual ~Subscriptor ()
Subscriptor & operator= (const Subscriptor &)
Subscriptor & operator= (Subscriptor &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Protected Member Functions
virtual void assemble_system_one_cell (const typename DoFHandler< dim >::active_cell_iterator &cell, ScratchData &scratch, CopyData &copy)
virtual void copy_one_cell (const CopyData &copy)
void make_grid ()
virtual void solve ()
virtual void estimate ()
void mark ()
void refine_grid ()
virtual void setup_system ()
virtual void assemble_system ()
virtual void output_results (const unsigned cycle) const
Protected Attributes
boost::signals2::signal< void()> setup_system_call_back
boost::signals2::signal< void(DataOut< dim > &)> add_data_vector
const unsigned int n_components
MPI_Comm mpi_communicator
int number_of_threads = -1
ConditionalOStream pcout
TimerOutput timer
parallel::distributed::Triangulation< dim > triangulation
std::unique_ptr< FiniteElement< dim > > fe
std::unique_ptr< MappingQGeneric< dim > > mapping
DoFHandler< dim > dof_handler
AffineConstraints< double > constraints
IndexSet locally_owned_dofs
IndexSet locally_relevant_dofs
LA::MPI::SparseMatrix system_matrix
LA::MPI::Vector locally_relevant_solution
LA::MPI::Vector solution
LA::MPI::Vector system_rhs
Vector< float > error_per_cell
std::string estimator_type = "exact"
std::string marking_strategy = "global"
std::pair< double, double > coarsening_and_refinement_factors = {0.03, 0.3}
FunctionParser< dim > pre_refinement
FunctionParser< dim > forcing_term
FunctionParser< dim > exact_solution
FunctionParser< dim > dirichlet_boundary_condition
FunctionParser< dim > neumann_boundary_condition
std::string fe_name = "FE_Q(1)"
unsigned int mapping_degree = 1
unsigned int n_refinements = 4
unsigned int n_refinement_cycles = 1
std::string output_filename = "linear_elasticity"
std::set< types::boundary_id > dirichlet_ids = {0}
std::set< types::boundary_id > neumann_ids
std::map< std::string, double > constants
std::string forcing_term_expression = "1"
std::string exact_solution_expression = "0"
std::string dirichlet_boundary_conditions_expression = "0"
std::string neumann_boundary_conditions_expression = "0"
std::string pre_refinement_expression = "0"
std::string grid_generator_function = "hyper_cube"
std::string grid_generator_arguments = "0: 1: false"
ParsedConvergenceTable error_table
ParameterAcceptorProxy< ReductionControl > solver_control
Protected Attributes inherited from ParameterAcceptor
const std::string section_name
std::vector< std::string > subsections
Friends
template<typename Integral >
class BaseProblemTester
Additional Inherited Members
Static Public Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from Subscriptor
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Public Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
Static Public Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Detailed Description
template<int dim>
class BaseProblem< dim >
Solve the Poisson problem, with Dirichlet or Neumann boundary conditions, on all geometries that can be generated by the functions in the GridGenerator namespace.
Definition at line 110 of file base_problem.h.
Member Typedef Documentation
CopyData
template<int dim> using BaseProblem< dim >::CopyData = MeshWorker::CopyData<1, 1, 1>
CopyDataWorkStream
Definition at line 158 of file base_problem.h.
ScratchData
template<int dim> using BaseProblem< dim >::ScratchData = MeshWorker::ScratchData<dim>
ScratchData
Definition at line 162 of file base_problem.h.
Constructor & Destructor Documentation
BaseProblem()
template<int dim> BaseProblem< dim >::BaseProblem (const unsigned int & n_components = 1, const std::string & problem_name = "")
Definition at line 27 of file base_problem.cc.
References ParameterAcceptor::add_parameter(), ParsedConvergenceTable::add_parameters(), BaseProblem< dim >::coarsening_and_refinement_factors, BaseProblem< dim >::constants, BaseProblem< dim >::dirichlet_boundary_conditions_expression, BaseProblem< dim >::dirichlet_ids, e(), ParameterHandler::enter_subsection(), BaseProblem< dim >::error_table, BaseProblem< dim >::estimator_type, BaseProblem< dim >::exact_solution_expression, BaseProblem< dim >::fe_name, BaseProblem< dim >::forcing_term_expression, BaseProblem< dim >::grid_generator_arguments, BaseProblem< dim >::grid_generator_function, ParameterHandler::leave_subsection(), BaseProblem< dim >::mapping_degree, BaseProblem< dim >::marking_strategy, BaseProblem< dim >::n_refinement_cycles, BaseProblem< dim >::n_refinements, BaseProblem< dim >::neumann_boundary_conditions_expression, BaseProblem< dim >::neumann_ids, BaseProblem< dim >::number_of_threads, BaseProblem< dim >::output_filename, BaseProblem< dim >::pre_refinement_expression, ParameterAcceptor::prm, this_mpi_process(), BaseProblem< dim >::timer, and triangulation.
~BaseProblem()
template<int dim> virtual BaseProblem< dim >::~BaseProblem () virtual default
Virtual destructor.
Member Function Documentation
assemble_system()
template<int dim> void BaseProblem< dim >::assemble_system protected virtual
MPI Threads
Reimplemented in BaseBlockProblem< dim >.
Definition at line 246 of file base_problem.cc.
References VectorOperation::add, copy(), WorkStream::run(), update_gradients, update_JxW_values, update_quadrature_points, and update_values.
assemble_system_one_cell()
template<int dim> void BaseProblem< dim >::assemble_system_one_cell (const typename DoFHandler< dim >::active_cell_iterator & cell, ScratchData & scratch, CopyData & copy) protected virtual
cellFEValuesscratchcopy WorkStream
Parameters
cell rhs
scratch Scratch object.
copy Copy object.
Reimplemented in Stokes< dim >, Poisson< dim >, Poisson< Integral::value >, BaseBlockProblem< dim >, and LinearElasticity< dim >.
Definition at line 221 of file base_problem.cc.
References Assert, and ExcPureFunctionCalled().
copy_one_cell()
template<int dim> void BaseProblem< dim >::copy_one_cell (const CopyData & copy) protected virtual
assemble_system_on_cell()rhs
Parameters
copy rhs
Reimplemented in BaseBlockProblem< dim >.
Definition at line 233 of file base_problem.cc.
References copy().
estimate()
template<int dim> void BaseProblem< dim >::estimate protected virtual
error_per_cell
Reimplemented in Stokes< dim >.
Definition at line 314 of file base_problem.cc.
References AssertThrow, cell_index, KellyErrorEstimator< dim, spacedim >::estimate(), ExcNotImplemented(), FEValues< dim >::get_function_laplacians(), VectorTools::H1_seminorm, VectorTools::integrate_difference(), FEValues< dim >::JxW(), FEValues< dim >::quadrature_point(), FEValues< dim >::quadrature_point_indices(), FEValues< dim >::reinit(), QGauss< dim >::size(), update_hessians, update_JxW_values, and update_quadrature_points.
initialize()
template<int dim> void BaseProblem< dim >::initialize (const std::string & filename)
Parameters
filename .
Definition at line 93 of file base_problem.cc.
References ParameterAcceptor::initialize(), and ParameterHandler::Short.
make_grid()
template<int dim> void BaseProblem< dim >::make_grid protected
Definition at line 116 of file base_problem.cc.
References GridGenerator::generate_from_name_and_arguments(), and triangulation.
mark()
template<int dim> void BaseProblem< dim >::mark protected
Definition at line 413 of file base_problem.cc.
References Assert, ExcInternalError(), parallel::distributed::GridRefinement::refine_and_coarsen_fixed_fraction(), parallel::distributed::GridRefinement::refine_and_coarsen_fixed_number(), and triangulation.
output_results()
template<int dim> void BaseProblem< dim >::output_results (const unsigned cycle) const protected virtual
ParaviewVisit
Parameters
cycle
Definition at line 463 of file base_problem.cc.
References DataOut< dim >::add_data_vector(), DataOut< dim >::attach_dof_handler(), DataOut< dim >::build_patches(), DataOut< dim >::set_flags(), triangulation, DataOutBase::VtkFlags::write_higher_order_cells, GridOut::write_mesh_per_processor_as_vtu(), and DataOut< dim >::write_vtu_in_parallel().
parse_string()
template<int dim> void BaseProblem< dim >::parse_string (const std::string & par)
Parameters
par
Definition at line 105 of file base_problem.cc.
References ParameterAcceptor::parse_all_parameters(), ParameterHandler::parse_input_from_string(), and ParameterAcceptor::prm.
print_system_info()
template<int dim> void BaseProblem< dim >::print_system_info
dofs
Definition at line 491 of file base_problem.cc.
References MultithreadInfo::n_cores(), Utilities::MPI::n_mpi_processes(), MultithreadInfo::n_threads(), MultithreadInfo::set_thread_limit(), and Utilities::MPI::this_mpi_process().
refine_grid()
template<int dim> void BaseProblem< dim >::refine_grid protected
Definition at line 142 of file base_problem.cc.
References triangulation.
run()
template<int dim> void BaseProblem< dim >::run
Definition at line 511 of file base_problem.cc.
setup_system()
template<int dim> void BaseProblem< dim >::setup_system protected virtual
Reimplemented in BaseBlockProblem< dim >.
Definition at line 153 of file base_problem.cc.
References SparsityTools::distribute_sparsity_pattern(), DoFTools::extract_locally_relevant_dofs(), VectorTools::interpolate_boundary_values(), locally_owned_dofs(), DoFTools::make_hanging_node_constraints(), DoFTools::make_sparsity_pattern(), and triangulation.
solve()
template<int dim> void BaseProblem< dim >::solve protected virtual
Reimplemented in Stokes< dim >, and BaseBlockProblem< dim >.
Definition at line 299 of file base_problem.cc.
References SolverCG< VectorType >::solve().
Friends And Related Function Documentation
BaseProblemTester
template<int dim> template<typename Integral > friend class BaseProblemTester friend
Definition at line 476 of file base_problem.h.
Member Data Documentation
add_data_vector
template<int dim> boost::signals2::signal<void(DataOut<dim> &)> BaseProblem< dim >::add_data_vector protected
Definition at line 236 of file base_problem.h.
Referenced by LinearElasticity< dim >::LinearElasticity(), Poisson< dim >::Poisson(), and Stokes< dim >::Stokes().
coarsening_and_refinement_factors
template<int dim> std::pair<double, double> BaseProblem< dim >::coarsening_and_refinement_factors = {0.03, 0.3} protected
Definition at line 360 of file base_problem.h.
Referenced by BaseProblem< dim >::BaseProblem().
constants
template<int dim> std::map<std::string, double> BaseProblem< dim >::constants protected
Definition at line 425 of file base_problem.h.
Referenced by BaseProblem< dim >::BaseProblem(), and Poisson< dim >::Poisson().
constraints
template<int dim> AffineConstraints<double> BaseProblem< dim >::constraints protected
Definition at line 307 of file base_problem.h.
dirichlet_boundary_condition
template<int dim> FunctionParser<dim> BaseProblem< dim >::dirichlet_boundary_condition protected
dirichlet
Definition at line 380 of file base_problem.h.
dirichlet_boundary_conditions_expression
template<int dim> std::string BaseProblem< dim >::dirichlet_boundary_conditions_expression = "0" protected
Dirichlet
Definition at line 440 of file base_problem.h.
Referenced by BaseProblem< dim >::BaseProblem().
dirichlet_ids
template<int dim> std::set<types::boundary_id> BaseProblem< dim >::dirichlet_ids = {0} protected
id
Definition at line 415 of file base_problem.h.
Referenced by BaseProblem< dim >::BaseProblem().
dof_handler
template<int dim> DoFHandler<dim> BaseProblem< dim >::dof_handler protected
Definition at line 302 of file base_problem.h.
error_per_cell
template<int dim> Vector<float> BaseProblem< dim >::error_per_cell protected
triangulation.n_active_cells() estimate()
Definition at line 345 of file base_problem.h.
error_table
template<int dim> ParsedConvergenceTable BaseProblem< dim >::error_table protected
Definition at line 465 of file base_problem.h.
Referenced by BaseProblem< dim >::BaseProblem().
estimator_type
template<int dim> std::string BaseProblem< dim >::estimator_type = "exact" protected
" "" " " "
Definition at line 350 of file base_problem.h.
Referenced by BaseProblem< dim >::BaseProblem().
exact_solution
template<int dim> FunctionParser<dim> BaseProblem< dim >::exact_solution protected
Definition at line 375 of file base_problem.h.
exact_solution_expression
template<int dim> std::string BaseProblem< dim >::exact_solution_expression = "0" protected
Definition at line 435 of file base_problem.h.
Referenced by BaseProblem< dim >::BaseProblem().
fe
template<int dim> std::unique_ptr<FiniteElement<dim> > BaseProblem< dim >::fe protected
Definition at line 290 of file base_problem.h.
fe_name
template<int dim> std::string BaseProblem< dim >::fe_name = "FE_Q(1)" protected
FETools::get_fe_by_name()
Definition at line 390 of file base_problem.h.
Referenced by BaseProblem< dim >::BaseProblem().
forcing_term
template<int dim> FunctionParser<dim> BaseProblem< dim >::forcing_term protected
Definition at line 370 of file base_problem.h.
forcing_term_expression
template<int dim> std::string BaseProblem< dim >::forcing_term_expression = "1" protected
Definition at line 430 of file base_problem.h.
Referenced by BaseProblem< dim >::BaseProblem().
grid_generator_arguments
template<int dim> std::string BaseProblem< dim >::grid_generator_arguments = "0: 1: false" protected
GridGenerator
Definition at line 460 of file base_problem.h.
Referenced by BaseProblem< dim >::BaseProblem().
grid_generator_function
template<int dim> std::string BaseProblem< dim >::grid_generator_function = "hyper_cube" protected
GridGenerator
Definition at line 455 of file base_problem.h.
Referenced by BaseProblem< dim >::BaseProblem().
locally_owned_dofs
template<int dim> IndexSet BaseProblem< dim >::locally_owned_dofs protected
MPI
Definition at line 313 of file base_problem.h.
locally_relevant_dofs
template<int dim> IndexSet BaseProblem< dim >::locally_relevant_dofs protected
Definition at line 318 of file base_problem.h.
locally_relevant_solution
template<int dim> LA::MPI::Vector BaseProblem< dim >::locally_relevant_solution protected
Definition at line 328 of file base_problem.h.
Referenced by LinearElasticity< dim >::LinearElasticity(), and Poisson< dim >::Poisson().
mapping
template<int dim> std::unique_ptr<MappingQGeneric<dim> > BaseProblem< dim >::mapping protected
Definition at line 297 of file base_problem.h.
mapping_degree
template<int dim> unsigned int BaseProblem< dim >::mapping_degree = 1 protected
Definition at line 395 of file base_problem.h.
Referenced by BaseProblem< dim >::BaseProblem().
marking_strategy
template<int dim> std::string BaseProblem< dim >::marking_strategy = "global" protected
"""_"Dorfler "_"
Definition at line 355 of file base_problem.h.
Referenced by BaseProblem< dim >::BaseProblem().
mpi_communicator
template<int dim> MPI_Comm BaseProblem< dim >::mpi_communicator protected
mpi .
Definition at line 262 of file base_problem.h.
n_components
template<int dim> const unsigned int BaseProblem< dim >::n_components protected
Definition at line 257 of file base_problem.h.
Referenced by LinearElasticity< dim >::LinearElasticity().
n_refinement_cycles
template<int dim> unsigned int BaseProblem< dim >::n_refinement_cycles = 1 protected
---
Definition at line 405 of file base_problem.h.
Referenced by BaseProblem< dim >::BaseProblem().
n_refinements
template<int dim> unsigned int BaseProblem< dim >::n_refinements = 4 protected
Definition at line 400 of file base_problem.h.
Referenced by BaseProblem< dim >::BaseProblem().
neumann_boundary_condition
template<int dim> FunctionParser<dim> BaseProblem< dim >::neumann_boundary_condition protected
neumann
Definition at line 385 of file base_problem.h.
neumann_boundary_conditions_expression
template<int dim> std::string BaseProblem< dim >::neumann_boundary_conditions_expression = "0" protected
Neumann
Definition at line 445 of file base_problem.h.
Referenced by BaseProblem< dim >::BaseProblem().
neumann_ids
template<int dim> std::set<types::boundary_id> BaseProblem< dim >::neumann_ids protected
id
Definition at line 420 of file base_problem.h.
Referenced by BaseProblem< dim >::BaseProblem().
number_of_threads
template<int dim> int BaseProblem< dim >::number_of_threads = -1 protected
Definition at line 267 of file base_problem.h.
Referenced by BaseProblem< dim >::BaseProblem().
output_filename
template<int dim> std::string BaseProblem< dim >::output_filename = "linear_elasticity" protected
Definition at line 410 of file base_problem.h.
Referenced by BaseProblem< dim >::BaseProblem().
pcout
template<int dim> ConditionalOStream BaseProblem< dim >::pcout protected
Definition at line 272 of file base_problem.h.
pre_refinement
template<int dim> FunctionParser<dim> BaseProblem< dim >::pre_refinement protected
n_refimement
Definition at line 365 of file base_problem.h.
pre_refinement_expression
template<int dim> std::string BaseProblem< dim >::pre_refinement_expression = "0" protected
pre-refinement
Definition at line 450 of file base_problem.h.
Referenced by BaseProblem< dim >::BaseProblem().
setup_system_call_back
template<int dim> boost::signals2::signal<void()> BaseProblem< dim >::setup_system_call_back protected
setup_system()
Definition at line 231 of file base_problem.h.
Referenced by Poisson< dim >::Poisson().
solution
template<int dim> LA::MPI::Vector BaseProblem< dim >::solution protected
Definition at line 333 of file base_problem.h.
solver_control
template<int dim> ParameterAcceptorProxy<ReductionControl> BaseProblem< dim >::solver_control protected
Definition at line 470 of file base_problem.h.
system_matrix
template<int dim> LA::MPI::SparseMatrix BaseProblem< dim >::system_matrix protected
Definition at line 323 of file base_problem.h.
system_rhs
template<int dim> LA::MPI::Vector BaseProblem< dim >::system_rhs protected
Definition at line 338 of file base_problem.h.
timer
template<int dim> TimerOutput BaseProblem< dim >::timer mutable protected
Definition at line 277 of file base_problem.h.
Referenced by BaseProblem< dim >::BaseProblem().
triangulation
template<int dim> parallel::distributed::Triangulation<dim> BaseProblem< dim >::triangulation protected
Definition at line 282 of file base_problem.h.
The documentation for this class was generated from the following files:
/github/workspace/include/base_problem.h
/github/workspace/source/base_problem.cc