add_test( [==[PoissonTester/std::integral_constant<int, 1>.MakeGrid]==] /workspaces/deal.ii-course-practice/build-container/gtest [==[--gtest_filter=PoissonTester/0.MakeGrid]==] --gtest_also_run_disabled_tests)
set_tests_properties( [==[PoissonTester/std::integral_constant<int, 1>.MakeGrid]==] PROPERTIES WORKING_DIRECTORY /workspaces/deal.ii-course-practice/build-container)
add_test( [==[PoissonTester/std::integral_constant<int, 2>.MakeGrid]==] /workspaces/deal.ii-course-practice/build-container/gtest [==[--gtest_filter=PoissonTester/1.MakeGrid]==] --gtest_also_run_disabled_tests)
set_tests_properties( [==[PoissonTester/std::integral_constant<int, 2>.MakeGrid]==] PROPERTIES WORKING_DIRECTORY /workspaces/deal.ii-course-practice/build-container)
add_test( [==[PoissonTester/std::integral_constant<int, 3>.MakeGrid]==] /workspaces/deal.ii-course-practice/build-container/gtest [==[--gtest_filter=PoissonTester/2.MakeGrid]==] --gtest_also_run_disabled_tests)
set_tests_properties( [==[PoissonTester/std::integral_constant<int, 3>.MakeGrid]==] PROPERTIES WORKING_DIRECTORY /workspaces/deal.ii-course-practice/build-container)
add_test( Poisson2DTester.TestLinear /workspaces/deal.ii-course-practice/build-container/gtest [==[--gtest_filter=Poisson2DTester.TestLinear]==] --gtest_also_run_disabled_tests)
set_tests_properties( Poisson2DTester.TestLinear PROPERTIES WORKING_DIRECTORY /workspaces/deal.ii-course-practice/build-container)
add_test( Poisson2DTester.TestQuadratic /workspaces/deal.ii-course-practice/build-container/gtest [==[--gtest_filter=Poisson2DTester.TestQuadratic]==] --gtest_also_run_disabled_tests)
set_tests_properties( Poisson2DTester.TestQuadratic PROPERTIES WORKING_DIRECTORY /workspaces/deal.ii-course-practice/build-container)
add_test( Poisson2DTester.TestMixedBC1 /workspaces/deal.ii-course-practice/build-container/gtest [==[--gtest_filter=Poisson2DTester.TestMixedBC1]==] --gtest_also_run_disabled_tests)
set_tests_properties( Poisson2DTester.TestMixedBC1 PROPERTIES WORKING_DIRECTORY /workspaces/deal.ii-course-practice/build-container)
add_test( Poisson2DTester.TestLinearWithHangingNodes /workspaces/deal.ii-course-practice/build-container/gtest [==[--gtest_filter=Poisson2DTester.TestLinearWithHangingNodes]==] --gtest_also_run_disabled_tests)
set_tests_properties( Poisson2DTester.TestLinearWithHangingNodes PROPERTIES WORKING_DIRECTORY /workspaces/deal.ii-course-practice/build-container)
add_test( Poisson2DTester.TestLinearWithHangingNodesUsingPars /workspaces/deal.ii-course-practice/build-container/gtest [==[--gtest_filter=Poisson2DTester.TestLinearWithHangingNodesUsingPars]==] --gtest_also_run_disabled_tests)
set_tests_properties( Poisson2DTester.TestLinearWithHangingNodesUsingPars PROPERTIES WORKING_DIRECTORY /workspaces/deal.ii-course-practice/build-container)
set( gtest_TESTS [==[PoissonTester/std::integral_constant<int, 1>.MakeGrid]==] [==[PoissonTester/std::integral_constant<int, 2>.MakeGrid]==] [==[PoissonTester/std::integral_constant<int, 3>.MakeGrid]==] Poisson2DTester.TestLinear Poisson2DTester.TestQuadratic Poisson2DTester.TestMixedBC1 Poisson2DTester.TestLinearWithHangingNodes Poisson2DTester.TestLinearWithHangingNodesUsingPars)
