add_test( [==[PoissonTester/std::integral_constant<int, 1>.MakeGrid]==] /workspaces/deal.ii-course-practice/build-container/gtest [==[--gtest_filter=PoissonTester/0.MakeGrid]==] --gtest_also_run_disabled_tests)
set_tests_properties( [==[PoissonTester/std::integral_constant<int, 1>.MakeGrid]==] PROPERTIES WORKING_DIRECTORY /workspaces/deal.ii-course-practice/build-container)
add_test( [==[PoissonTester/std::integral_constant<int, 2>.MakeGrid]==] /workspaces/deal.ii-course-practice/build-container/gtest [==[--gtest_filter=PoissonTester/1.MakeGrid]==] --gtest_also_run_disabled_tests)
set_tests_properties( [==[PoissonTester/std::integral_constant<int, 2>.MakeGrid]==] PROPERTIES WORKING_DIRECTORY /workspaces/deal.ii-course-practice/build-container)
add_test( [==[PoissonTester/std::integral_constant<int, 3>.MakeGrid]==] /workspaces/deal.ii-course-practice/build-container/gtest [==[--gtest_filter=PoissonTester/2.MakeGrid]==] --gtest_also_run_disabled_tests)
set_tests_properties( [==[PoissonTester/std::integral_constant<int, 3>.MakeGrid]==] PROPERTIES WORKING_DIRECTORY /workspaces/deal.ii-course-practice/build-container)
add_test( Poisson2DTester.MakeGrid /workspaces/deal.ii-course-practice/build-container/gtest [==[--gtest_filter=Poisson2DTester.MakeGrid]==] --gtest_also_run_disabled_tests)
set_tests_properties( Poisson2DTester.MakeGrid PROPERTIES WORKING_DIRECTORY /workspaces/deal.ii-course-practice/build-container)
set( gtest_TESTS [==[PoissonTester/std::integral_constant<int, 1>.MakeGrid]==] [==[PoissonTester/std::integral_constant<int, 2>.MakeGrid]==] [==[PoissonTester/std::integral_constant<int, 3>.MakeGrid]==] Poisson2DTester.MakeGrid)
