if(EXISTS "/workspaces/deal.ii-course-practice/build-container/gtest[1]_tests.cmake")
  include("/workspaces/deal.ii-course-practice/build-container/gtest[1]_tests.cmake")
else()
  add_test(gtest_NOT_BUILT gtest_NOT_BUILT)
endif()
