/* ---------------------------------------------------------------------
 *
 * Copyright (C) 1999 - 2020 by the deal.II authors
 *
 * This file is part of the deal.II library.
 *
 * The deal.II library is free software; you can use it, redistribute
 * it, and/or modify it under the terms of the GNU Lesser General
 * Public License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * The full text of the license can be found in the file LICENSE.md at
 * the top level directory of deal.II.
 *
 * ---------------------------------------------------------------------
 *
 * Authors: Wolfgang Bangerth, 1999,
 *          Guido Kanschat, 2011
 *          Luca Heltai, 2021
 */

// Make sure we don't redefine things
#ifndef poisson_include_file
#define poisson_include_file

#include "base_problem.h"
// Forward declare the tester class
template <typename Integral>
class PoissonTester;

using namespace dealii;

/**
 * Solve the Poisson problem, with Dirichlet or Neumann boundary conditions, on
 * all geometries that can be generated by the functions in the GridGenerator
 * namespace.
 */
template <int dim>
class Poisson : public BaseProblem<dim>
{
public:
  /**
   * Constructor. Initialize all parameters, including the base class, and make
   * sure the class is ready to run.
   */
  Poisson();

  /**
   * Destroy the Poisson object
   */
  virtual ~Poisson() = default;

  using ScratchData = typename BaseProblem<dim>::ScratchData;
  using CopyData    = typename BaseProblem<dim>::CopyData;

protected:
  /**
   * Explicitly assemble the Poisson problem.
   */
  virtual void
  assemble_system_one_cell(
    const typename DoFHandler<dim>::active_cell_iterator &cell,
    ScratchData &                                         scratch,
    CopyData &                                            copy) override;

  FunctionParser<dim> coefficient;
  std::string         coefficient_expression = "1";
  template <typename Integral>
  friend class PoissonTester;
};

#endif
